Server:
  RunMode: debug
  HttpPort: :8080
  ReadTimeout: 60
  WriteTimeout: 60
Redis:
  Address: 127.0.0.1
  Port: 6379
  Password: 123
  Database: 1
App:
  LogSavePath: D:\\log
  LogFileName: bdc
  LogFileExt: .log
